language: r
cache: packages
sudo: false
warnings_are_errors: false

install:
  - Rscript install-packages.R
  
script:
  - R -e 'setwd("DataCleaningScripts"); source("get_regional_weather.R"); append_regional_weather()'
  - Rscript testthat.R
  - R -e 'setwd("DataCleaningScripts"); source("new_weather_data.R"); append_weather()'
  - R -e 'setwd("DataCleaningScripts"); source("update_portal_rodent_trapping.r"); writetrappingtable()'
  - R -e 'setwd("DataCleaningScripts"); source("update_portal_plots.R"); writeportalplots()'
  - R -e 'setwd("DataCleaningScripts"); source("new_moon_numbers.r"); writenewmoons()'
  - R -e 'setwd("DataCleaningScripts"); source("update_portal_plant_censuses.R"); writecensustable()'
  - git checkout master
  - Rscript archive.R
  - git remote add deploytags https://${GITHUB_TOKEN}@github.com/weecology/PortalData.git > /dev/null 2>&1
  - git push --quiet deploytags --tags > /dev/null 2>&1
  - curl -v -i -X POST -H "Content-Type:application/json" -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/weecology/PortalData/releases -d "{\"tag_name\":\"$version\"}"
  
after_success:
